ui-tests: minimize Log window
On hosted GitHub Actions runners, there is always this Log window
visible on the Desktop, and due to some magic logic, this window is
sometimes in the foreground on the `windows-2025` runners.

Let's minimize it so that it is out of the way and does not interfere
with the AutoHotKey-based UI tests.

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>

diff --git a/.github/workflows/ui-tests.yml b/.github/workflows/ui-tests.yml
--- a/.github/workflows/ui-tests.yml
+++ b/.github/workflows/ui-tests.yml
@@ -96,6 +96,13 @@ jobs:
           "$WINDIR/system32/tar.exe" -C "$RUNNER_TEMP" -xvf "$RUNNER_TEMP/win32-openssh.zip" &&
           echo "OPENSSH_FOR_WINDOWS_DIRECTORY=$(cygpath -aw "$RUNNER_TEMP/OpenSSH-Win64")" >>$GITHUB_ENV
 
+      - name: Minimize existing Log window
+        working-directory: ui-tests
+        run: |
+          $exitCode = 0
+          & "${env:RUNNER_TEMP}\ahk\AutoHotKey64.exe" /ErrorStdOut /force minimize-log-window.ahk "$PWD\minimize-log-window" 2>&1 | Out-Default
+          if (!$?) { $exitCode = 1; echo "::error::Failed to minimize Log window!" } else { echo "::notice::Minimized Log window" }
+          exit $exitCode
       - name: Run UI tests
         id: ui-tests
         timeout-minutes: 10
